help:
	go run main.go -h
sub/cmd_test_args:
	go run main.go args -h
	go run main.go args 123 456
sub/cmd_test_flag:
	go run main.go flags -h
	go run main.go flags --name bobo --age 123 --sex
sub/cmd_test_file:
	go run main.go file -h
	go run main.go file -c config.yaml
