// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.17.1
// source: app/interface/rpc/v1.0/protocol/user_service.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListUserRequestType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListUserRequestType) Reset() {
	*x = ListUserRequestType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequestType) ProtoMessage() {}

func (x *ListUserRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequestType.ProtoReflect.Descriptor instead.
func (*ListUserRequestType) Descriptor() ([]byte, []int) {
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP(), []int{1}
}

type ListUserResponseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ListUserResponseType) Reset() {
	*x = ListUserResponseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponseType) ProtoMessage() {}

func (x *ListUserResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponseType.ProtoReflect.Descriptor instead.
func (*ListUserResponseType) Descriptor() ([]byte, []int) {
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserResponseType) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type RegisterUserResponseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterUserResponseType) Reset() {
	*x = RegisterUserResponseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponseType) ProtoMessage() {}

func (x *RegisterUserResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponseType.ProtoReflect.Descriptor instead.
func (*RegisterUserResponseType) Descriptor() ([]byte, []int) {
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP(), []int{3}
}

type RegisterUserRequestType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RegisterUserRequestType) Reset() {
	*x = RegisterUserRequestType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequestType) ProtoMessage() {}

func (x *RegisterUserRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequestType.ProtoReflect.Descriptor instead.
func (*RegisterUserRequestType) Descriptor() ([]byte, []int) {
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserRequestType) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_app_interface_rpc_v1_0_protocol_user_service_proto protoreflect.FileDescriptor

var file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2e, 0x30, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x2c,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x3c, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x32, 0xb3,
	0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b,
	0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2e, 0x30, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescOnce sync.Once
	file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescData = file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDesc
)

func file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescGZIP() []byte {
	file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescOnce.Do(func() {
		file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescData)
	})
	return file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDescData
}

var file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_interface_rpc_v1_0_protocol_user_service_proto_goTypes = []interface{}{
	(*User)(nil),                     // 0: protocol.User
	(*ListUserRequestType)(nil),      // 1: protocol.ListUserRequestType
	(*ListUserResponseType)(nil),     // 2: protocol.ListUserResponseType
	(*RegisterUserResponseType)(nil), // 3: protocol.RegisterUserResponseType
	(*RegisterUserRequestType)(nil),  // 4: protocol.RegisterUserRequestType
}
var file_app_interface_rpc_v1_0_protocol_user_service_proto_depIdxs = []int32{
	0, // 0: protocol.ListUserResponseType.users:type_name -> protocol.User
	1, // 1: protocol.UserService.ListUser:input_type -> protocol.ListUserRequestType
	4, // 2: protocol.UserService.RegisterUser:input_type -> protocol.RegisterUserRequestType
	2, // 3: protocol.UserService.ListUser:output_type -> protocol.ListUserResponseType
	3, // 4: protocol.UserService.RegisterUser:output_type -> protocol.RegisterUserResponseType
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_interface_rpc_v1_0_protocol_user_service_proto_init() }
func file_app_interface_rpc_v1_0_protocol_user_service_proto_init() {
	if File_app_interface_rpc_v1_0_protocol_user_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserRequestType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserResponseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserResponseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserRequestType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_interface_rpc_v1_0_protocol_user_service_proto_goTypes,
		DependencyIndexes: file_app_interface_rpc_v1_0_protocol_user_service_proto_depIdxs,
		MessageInfos:      file_app_interface_rpc_v1_0_protocol_user_service_proto_msgTypes,
	}.Build()
	File_app_interface_rpc_v1_0_protocol_user_service_proto = out.File
	file_app_interface_rpc_v1_0_protocol_user_service_proto_rawDesc = nil
	file_app_interface_rpc_v1_0_protocol_user_service_proto_goTypes = nil
	file_app_interface_rpc_v1_0_protocol_user_service_proto_depIdxs = nil
}
